version: '3.1'
services:
  persistent_store:
    image: postgres:14.1
    restart: 'always'
    environment:
      - POSTGRES_USER=reimar
      - POSTGRES_PASSWORD=reimar
      - POSTGRES_DB=imagiana
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/
  session_store:
    image: redis:7
    restart: 'always'
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
